project:
  type: website

website:
  title: "SustainableLiving"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: quartz

editor: visual

