project:
  type: website

website:
  favicon: pictures/logo.png
  title: "Sustainable Living"
  description: "A guide to living sustainably in college"
  cookie-consent: true
  google-analytics: 
   tracking-id: "G-YR77Q3KCY1"
   anonymize-ip: true
  navbar:
    logo: pictures/logo.png
    right:
      - href: eating.qmd
        text: Eating
      - href: creating.qmd
        text: Creating
      - href: learning.qmd
        text: Learning
      - href: reusing.qmd
        text: Reusing
      - href: about.qmd
        text: About

format:
  html:
    theme: lux.scss

editor: visual

