project:
  type: website

website:
  title: "SustainableLiving"
  description: "A guide to living sustainably in college"
  navbar:
    right:
      - href: eating.qmd
        text: Eating
      - href: creating.qmd
        text: Creating
      - href: learning.qmd
        text: Learning
      - href: reusing.qmd
        text: Reusing
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: quartz

editor: visual

