project:
  type: website

website:
  favicon: pictures/logo.png
  title: "Sustainable Living"
  description: "A guide to living sustainably in college"
  bread-crumbs: true
  cookie-consent: true
  google-analytics: 
   tracking-id: "G-YR77Q3KCY1"
   anonymize-ip: true
  navbar:
    logo: pictures/logo.png
    right:
      - href: eating.qmd
        text: Eating
      - href: creating.qmd
        text: Creating
      - href: learning.qmd
        text: Learning
      - href: reusing.qmd
        text: Reusing
      - href: art.qmd
        text: Art
      - href: about.qmd
        text: About
  page-footer: 
    left: "Sustainably Living: A Guide To Living Sustainably Through School"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/ally--olsen/

format:
  html:
    theme: lux.scss

editor: visual

