project:
  type: website

website:
  title: "Sustainable Living"
  description: "A guide to living sustainably in college"
  navbar:
    logo: pictures/logo.png
    right:
      - href: eating.qmd
        text: Eating
      - href: creating.qmd
        text: Creating
      - href: learning.qmd
        text: Learning
      - href: reusing.qmd
        text: Reusing
      - href: about.qmd
        text: About

format:
  html:
    theme: lux.scss
    css: style.css

editor: visual

